name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Run tests
        run: |
          python -m pytest tests/test_app.py
           working-directory: tests

      - name: Build Docker image
        run: docker build -m clicker_game:latest .
        working-directory: .
